import type { PubgAction, TriggerConfig } from "./types";

export const DEVICE = {
  name: "Galaxy Note 10+",
  model: "SM-N975U",
  chipset: "Snapdragon 855",
  ramGb: 12,
  storage: "256 GB UFS 3.0",
  display: '6.8" Dynamic AMOLED',
  resolution: "3040 × 1440",
  refresh: "60 Hz",
  touchNative: "120 Hz",
  battery: "4300 mAh",
  cooling: "Vapor chamber",
  spen: "4096-level S Pen",
  speakers: "AKG stereo",
} as const;

export const ACTION_LABEL: Record<PubgAction, string> = {
  fire: "Fire",
  ads: "ADS / Scope",
  jump: "Jump",
  crouch: "Crouch",
  prone: "Prone",
  reload: "Reload",
  peekL: "Peek left",
  peekR: "Peek right",
  grenade: "Throw",
  sprint: "Sprint",
  scope: "Hold breath",
  loot: "Loot",
  heal: "Heal",
  lean: "Lean",
};

export const PUBG_TRIGGERS: TriggerConfig[] = [
  {
    id: "L1",
    label: "Left shoulder",
    enabled: true,
    mode: "hold",
    action: "ads",
    action2: "scope",
    rapidCps: 5,
    along: 38,
    size: 46,
    sensitivity: 1,
    haptic: true,
    glow: true,
  },
  {
    id: "R1",
    label: "Right shoulder",
    enabled: true,
    mode: "tap",
    action: "fire",
    action2: "fire",
    rapidCps: 5,
    along: 38,
    size: 46,
    sensitivity: 1,
    haptic: true,
    glow: true,
  },
  {
    id: "SPEN",
    label: "S Pen button",
    enabled: true,
    mode: "tap",
    action: "grenade",
    action2: "loot",
    rapidCps: 3,
    along: 72,
    size: 28,
    sensitivity: 1,
    haptic: true,
    glow: false,
  },
];

export const GAMES = [
  {
    id: "pubg",
    title: "PUBG Mobile",
    tag: "Battle Royale",
    featured: true,
    hours: 186,
    ping: 38,
    fpsTarget: 60,
    preset: "Rise · Smooth + Ultra",
    note: "Primary profile. 4-finger claw + AI Smart Trigger.",
  },
  {
    id: "codm",
    title: "Call of Duty: Mobile",
    tag: "FPS",
    featured: false,
    hours: 42,
    ping: 44,
    fpsTarget: 60,
    preset: "Balance",
    note: "Competitive plugins can flag accounts.",
  },
  {
    id: "ff",
    title: "Free Fire",
    tag: "Battle Royale",
    featured: false,
    hours: 19,
    ping: 51,
    fpsTarget: 60,
    preset: "Rise",
    note: "High-sens wheel recommended.",
  },
  {
    id: "mlbb",
    title: "Mobile Legends",
    tag: "MOBA",
    featured: false,
    hours: 64,
    ping: 29,
    fpsTarget: 60,
    preset: "Balance",
    note: "Auxiliary line for skill ranges.",
  },
  {
    id: "genshin",
    title: "Genshin Impact",
    tag: "Open world",
    featured: false,
    hours: 11,
    ping: 62,
    fpsTarget: 45,
    preset: "Eco",
    note: "Thermal first on 855.",
  },
  {
    id: "range",
    title: "Forge Range",
    tag: "Trainer",
    featured: false,
    hours: 4,
    ping: 12,
    fpsTarget: 60,
    preset: "Diablo",
    note: "Built-in PUBG layout trainer.",
  },
] as const;

export const PLUGIN_META = [
  {
    id: "aiTrigger",
    name: "AI Smart Trigger",
    blurb: "Context assist: auto-reload, loot, heal, and optional auto-fire when a target is in reticle.",
    pubg: true,
    risk: "high" as const,
  },
  {
    id: "crosshair",
    name: "Crosshair overlay",
    blurb: "Center mark for hip-fire. Hide from a floating toggle.",
    pubg: true,
    risk: "low" as const,
  },
  {
    id: "audioProbe",
    name: "Audio / visual probes",
    blurb: "3D rings for footsteps and gunfire direction.",
    pubg: true,
    risk: "med" as const,
  },
  {
    id: "auxiliaryLine",
    name: "Auxiliary line",
    blurb: "Throw arc and distance rings for grenades and smokes.",
    pubg: true,
    risk: "med" as const,
  },
  {
    id: "stopwatch",
    name: "Stopwatch",
    blurb: "Zone timer plus knockdown revive countdown.",
    pubg: true,
    risk: "low" as const,
  },
  {
    id: "hunt",
    name: "Hunt filter",
    blurb: "Invert, night vision, or focus grade to pick enemies out of grass.",
    pubg: true,
    risk: "high" as const,
  },
  {
    id: "scout",
    name: "Scout mode",
    blurb: "Digital zoom on the aim point for long-range peeks.",
    pubg: true,
    risk: "med" as const,
  },
  {
    id: "dataPanel",
    name: "Data panel",
    blurb: "Live CPS, ADS time, and hand speed.",
    pubg: true,
    risk: "low" as const,
  },
  {
    id: "vibrate4d",
    name: "4D vibrate",
    blurb: "Scene haptics: recoil, knock, zone tick. Uses Note 10+ vibration motor.",
    pubg: true,
    risk: "low" as const,
  },
  {
    id: "highSensWheel",
    name: "High-sens wheel",
    blurb: "Replace the in-game stick with a shorter, faster wheel.",
    pubg: true,
    risk: "low" as const,
  },
  {
    id: "keyRemap",
    name: "Key remapping",
    blurb: "Drag HUD buttons. Map S Pen and edge triggers to any action.",
    pubg: true,
    risk: "low" as const,
  },
  {
    id: "superiorPic",
    name: "Superior pic quality",
    blurb: "Sharper buffers. Extra heat on Snapdragon 855 — keep sessions short.",
    pubg: true,
    risk: "low" as const,
  },
  {
    id: "soundEq",
    name: "Sound equalizer",
    blurb: "Boost 2–6 kHz for footsteps, cut bass rumble.",
    pubg: true,
    risk: "low" as const,
  },
  {
    id: "winRate",
    name: "Win-rate predictor",
    blurb: "Live placement odds from your K/D, zone, and loot in this match.",
    pubg: true,
    risk: "low" as const,
  },
  {
    id: "aiCoach",
    name: "AI coach",
    blurb: "Short callouts: rotate, heal, don't ego peek.",
    pubg: true,
    risk: "low" as const,
  },
  {
    id: "macros",
    name: "Macros",
    blurb: "Peek-fire, jump-crouch, and throw-swap bound to one press.",
    pubg: true,
    risk: "high" as const,
  },
  {
    id: "bulletShield",
    name: "Bullet shield",
    blurb: "Notifications become a tiny barrage or vanish entirely.",
    pubg: true,
    risk: "low" as const,
  },
  {
    id: "rotationLock",
    name: "Rotation lock",
    blurb: "Lock landscape and mute incoming calls.",
    pubg: true,
    risk: "low" as const,
  },
  {
    id: "gyroTap",
    name: "Somatosensory",
    blurb: "Tilt the Note 10+ to tap a mapped control — extra gyro layer.",
    pubg: true,
    risk: "med" as const,
  },
] as const;

export const MACROS = [
  { id: "peekfire", name: "Peek-fire", steps: "Peek L → Fire ×3 → Unpeek" },
  { id: "dropshot", name: "Drop shot", steps: "Crouch → Fire → Stand" },
  { id: "jumpcrouch", name: "Jump-crouch", steps: "Jump → Crouch-spam" },
  { id: "nade-swap", name: "Nade swap", steps: "Throw → Switch AR" },
] as const;

export const PERF_MODES = [
  {
    id: "eco" as const,
    name: "Eco",
    blurb: "Lock 40 FPS, dim the panel, skip Wi-Fi low-latency. Long ranked queues.",
  },
  {
    id: "balance" as const,
    name: "Balance",
    blurb: "Stock 855 clocks. Fine for Smooth + High.",
  },
  {
    id: "rise" as const,
    name: "Rise",
    blurb: "PUBG default. Sustained 60 on Smooth + Ultra, vapor chamber aggressive.",
  },
  {
    id: "diablo" as const,
    name: "Diablo",
    blurb: "Max clocks. Training bursts only — 855 will thermal after a few minutes.",
  },
];
